"""Price to token in users

Revision ID: 93aee512627a
Revises: 5c39746c4a4a
Create Date: 2025-06-04 11:08:43.766900

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '93aee512627a'
down_revision = '5c39746c4a4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tokens', sa.Float(precision=2), nullable=False))
        batch_op.drop_column('cash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cash', mysql.FLOAT(), nullable=False))
        batch_op.drop_column('tokens')

    # ### end Alembic commands ###
